language: node_js
node_js:
- '10'
before_install:
- npm install -g typescript codecov tsc rollup
script:
- npm test
before_deploy:
- npm run build
- cd ./dist
deploy:
  provider: npm
  email: dale@daleslab.com
  api_key:
    secure: R1nx2RWAmtitsOGoNRT+G9cNW+w/s1Q5mPovYvcyv14XKv8XnqAif0bJ8RmWYEPAFKo5kfxbjX7NgPeDeRx+ETyIGErRkbVM7jTU0qVDcYGrETR1uC3wA0tH0OOxOh2TZedFmQLMbpsfqkG4dDT8GqaVbij8RPmaGaotFdld84r9A3JvKNyCsY+ulP2KlUmw9Lm54CqjrzFDJHkruYgZ3iaQtQHByOCJS9E1js1guxudUTRL4IwMwvwVlQaIk7J27Ue0AR/ubTrX3b7iCPlrL7XD9gA6xS0aYwJEBwweys3byPOC4rvc6KY7YiNFzUiL4wECgcYYogq9oEU2FEuimGtuXguIKQINx9Nd65zGyrLBbPxP7RSKDbceb/aiDgHe0mDlVNHUruqE1hVMR0hIHJVWbqFm1PUTcZyNqo6YA6+Oa8i2UL6YqdUihrASOJnwZArCcmDjGswPonMa8axCKIOfrX3x/CGS3CwtPVVsKmcwKPEAoYtwNzbjlEvpPhy2O+NGpu7AqcwZCIR/u5EdIQfMzhUN3zRhOklXaIThFXCX6uPakU+hGPxz3UQ2x+CEjwb/XuAnukVlUCtVQzcZ+VwE4BEFzKvkYv5QWoj3f7PCjpX66f6QlqEfyhgZz1gzGuFLecaAFSKMElrqPkt35UdffcC6Zbl3o1VmXA1aoYw=
  on:
    tags: true
    repo: BendroCorp/bendrocorp-node-sdk
notifications:
  slack:
    rooms:
      secure: R5ol9J1SZDUKEMzWTnEA5Qk/x5ZPYdU2esV05uw1Jyuv1oLQXQVPDSr/ZP1pIxgrx8fwVUa61Xo9NIum0meQFWn9ru0qkkiEbfTRpMJiCDF8L2Qa0dr7JbFAoQ8Zazht4B0I0y4cnBVeM0XcUpWFdb8rOF6v7eOx/bOGLJHKu7v1LsmFlQ6RJEpZj0Vjk5KPokOsgB1cAukvkCt+5jVitBve7nyMeCalMEgpR1L+vkhRgS5adh56zvq9XISRat4jq+A9ePvlzGBJVJTuP18CHlEFU0my0MagPsrIP1UIaJK/xSb7bj60brlFfSzPc0bMBsal4H8RnxBF84KI7Makm5464KUQYC+1gIW7Ie+S10O9cfG5e0PQD8oqNkpno2fjGdU1bqjHsIT6Jq2WLZocgyM8RWbPD1mnmz9ov6QYLVxKxRVAb6IFDzur9EePmcDLPASrkBr0CnvhhT6uHZISuFRd9ZVQxgOH4hUJaQq93qubeDvYra/+h2Ly+9tZwS6Obd/VYV+L5G/DB1ryh5Q5t5/rtQBadYV/R6yI7x3Dr1WIvOEKVriD7immqXuWA134WE7lWea2YiaZfO8esJ3iyqtae/F07zDN2iSMo24xGrZV3/fPqGa5uI6ngfNMcCHw4NYocT1pbV9VdITpnFzSuX3AViVEouD2/R9CXrbnCF0=
